Added succesfull step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -15,13 +15,13 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed step
-        run: |
-          echo "I will fail"
-          exit 1
-      # - name: Successful step
+      # - name: Failed step
       #   run: |
-      #     echo "I will succeed"
-      #     exit 0
+      #     echo "I will fail"
+      #     exit 1
+      - name: Successful step
+        run: |
+          echo "I will succeed"
+          exit 0
       - name: Say goodbye
         run: echo "Goodbye!"
